/**
 * Filesystem safety tests.
 *
 * These cover the two guarantees that matter: the renderer cannot escape a
 * granted folder, and a tag write never leaves a damaged original behind.
 */
import { createRequire } from "node:module";
import { mkdtempSync, rmSync, copyFileSync, existsSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const require = createRequire(import.meta.url);
const files = require("./files.cjs");
const NodeID3 = require("node-id3");
const { readFlacComments, parseBlocks } = require("./flac.cjs");

const here = path.dirname(fileURLToPath(import.meta.url));
const SOURCE_MP3 = path.resolve(here, "..", "..", "demo", "la-revoltoza.mp3");
const FIXTURE_FLAC = path.join(tmpdir(), "me-fixture.flac");

let root;
let target;
let flacTarget;

beforeAll(() => {
  root = mkdtempSync(path.join(tmpdir(), "me-files-"));
  mkdirSync(path.join(root, "sub"), { recursive: true });
  target = path.join(root, "sub", "track.mp3");
  copyFileSync(SOURCE_MP3, target);
  // A non-audio file and an unsupported audio format, to exercise filtering.
  writeFileSync(path.join(root, "notes.txt"), "not audio");
  // A real FLAC, generated by libsndfile, so the writer is tested against a
  // genuine container rather than a hand-made approximation.
  flacTarget = path.join(root, "real.flac");
  copyFileSync(FIXTURE_FLAC, flacTarget);
  files.grantRoot(root);
});

afterAll(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("permission boundary", () => {
  it("permits paths inside a granted root", () => {
    expect(files.isPermitted(target)).toBe(true);
  });

  it("refuses paths outside every granted root", () => {
    expect(files.isPermitted(path.join(tmpdir(), "elsewhere.mp3"))).toBe(false);
    expect(files.isPermitted(String.raw`C:\Windows\System32\config\SAM`)).toBe(false);
  });

  it("refuses a traversal that climbs out of the root", () => {
    expect(files.isPermitted(path.join(root, "..", "..", "secret.mp3"))).toBe(false);
  });

  it("rejects a read outside the root", async () => {
    await expect(files.readFile(path.join(tmpdir(), "nope.mp3"))).rejects.toThrow(/outside/i);
  });

  it("rejects a write outside the root", async () => {
    const result = await files.writeTags(path.join(tmpdir(), "nope.mp3"), { bpm: "128" });
    expect(result.ok).toBe(false);
  });
});

describe("scanFolder", () => {
  it("finds audio recursively and skips non-audio", async () => {
    const { files: found } = await files.scanFolder(root);
    const names = found.map((f) => f.name);
    expect(names).toContain("track.mp3");
    expect(names).toContain("real.flac");
    expect(names).not.toContain("notes.txt");
  });

  it("reports POSIX-style relative paths", async () => {
    const { files: found } = await files.scanFolder(root);
    expect(found.find((f) => f.name === "track.mp3").relativePath).toBe("sub/track.mp3");
  });

  it("reports real sizes", async () => {
    const { files: found } = await files.scanFolder(root);
    expect(found.find((f) => f.name === "track.mp3").sizeBytes).toBe(statSync(target).size);
  });
});

describe("writeTags", () => {
  it("refuses a format it cannot write", async () => {
    writeFileSync(path.join(root, "other.m4a"), "fake m4a");
    const result = await files.writeTags(path.join(root, "other.m4a"), { bpm: "128" });
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/no tag writer/i);
  });

  it("refuses an empty payload rather than rewriting the file for nothing", async () => {
    const result = await files.writeTags(target, {});
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/nothing selected/i);
  });

  it("writes frames and reads them back", async () => {
    const result = await files.writeTags(target, { bpm: "128", initialKey: "Am" });
    expect(result.ok).toBe(true);
    const tags = NodeID3.read(target);
    expect(String(tags.bpm)).toBe("128");
    expect(tags.initialKey).toBe("Am");
  });

  it("backs the original up before the first write", async () => {
    const backup = path.join(root, "sub", ".music-editor-backups", "track.mp3");
    expect(existsSync(backup)).toBe(true);
    // The backup must be the pristine file, not the tagged one.
    expect(readFileSync(backup).equals(readFileSync(SOURCE_MP3))).toBe(true);
  });

  it("keeps the first backup instead of overwriting it on a second write", async () => {
    const backup = path.join(root, "sub", ".music-editor-backups", "track.mp3");
    const before = readFileSync(backup);
    const result = await files.writeTags(target, { bpm: "140" });
    expect(result.ok).toBe(true);
    expect(result.backupCreated).toBe(false);
    // Still the untouched original, so a revert always reaches the real source.
    expect(readFileSync(backup).equals(before)).toBe(true);
    expect(String(NodeID3.read(target).bpm)).toBe("140");
  });

  it("leaves no temporary file behind", async () => {
    await files.writeTags(target, { bpm: "126" });
    expect(existsSync(`${target}.musiceditor.tmp`)).toBe(false);
  });

  it("leaves the original playable and intact after writes", async () => {
    // The audio payload must survive tagging; only the ID3 container changes.
    const tagged = readFileSync(target);
    expect(tagged.length).toBeGreaterThan(1000);
    expect(NodeID3.read(target)).toBeTruthy();
  });

  it("does not damage the original when the write fails", async () => {
    const before = readFileSync(target);
    const result = await files.writeTags(target, {});
    expect(result.ok).toBe(false);
    expect(readFileSync(target).equals(before)).toBe(true);
  });
});

describe("FLAC tagging", () => {
  it("writes Vorbis comments and reads them back", async () => {
    const result = await files.writeTags(flacTarget, { bpm: "128", initialKey: "Am" });
    expect(result.ok).toBe(true);
    const tags = readFlacComments(readFileSync(flacTarget));
    expect(tags.BPM).toBe("128");
    expect(tags.KEY).toBe("Am");
    expect(tags.INITIALKEY).toBe("Am");
  });

  it("leaves the file decodable", async () => {
    // The audio frames and STREAMINFO must survive a metadata rewrite.
    const { blocks, audio } = parseBlocks(readFileSync(flacTarget));
    expect(blocks[0].type).toBe(0); // STREAMINFO must still come first
    expect(audio.length).toBeGreaterThan(1000);
    expect(readFileSync(flacTarget).subarray(0, 4).toString("ascii")).toBe("fLaC");
  });

  it("keeps unrelated comments when updating one field", async () => {
    await files.writeTags(flacTarget, { comment: "first" });
    await files.writeTags(flacTarget, { bpm: "140" });
    const tags = readFlacComments(readFileSync(flacTarget));
    expect(tags.COMMENT).toBe("first");
    expect(tags.BPM).toBe("140");
  });

  it("replaces rather than duplicates a repeated field", async () => {
    await files.writeTags(flacTarget, { bpm: "150" });
    const buffer = readFileSync(flacTarget);
    const { blocks } = parseBlocks(buffer);
    const comment = blocks.find((b) => b.type === 4);
    const occurrences = comment.data.toString("utf8").split("BPM=").length - 1;
    expect(occurrences).toBe(1);
    expect(readFlacComments(buffer).BPM).toBe("150");
  });

  it("backs up the FLAC before its first write", () => {
    expect(existsSync(path.join(root, ".music-editor-backups", "real.flac"))).toBe(true);
  });
});
